---
title: "Viz II"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(patchwork)
library(p8105.datasets)
```

Import the weather data

```{r}
data("weather_df")
```

Let's make our basic scatterplot

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.5) + 
  labs(
    x = "Minimum daily temp",
    y = "Maximum daily temp",
    title = "Temperature scatterplot", 
    caption = "Data from NOAA",
    color = "Location" # labeled the legend
  )
```


## Scales

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.5) + 
  labs(
    x = "Minimum daily temp",
    y = "Maximum daily temp",
    title = "Temperature scatterplot", 
    caption = "Data from NOAA",
    color = "Location"
  ) + 
  scale_x_continuous( # the scale is continuous here
    breaks = c(-20, 0, 25), # scale axis numbers
    labels = c("-20C", "0", "25") # labels for scale axis
  ) + 
  viridis::scale_color_viridis( # pulls out color palette
    discrete = TRUE
  )
```


## Themes

Make my base plot.

```{r}
ggp_temperature = 
  weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.5) + 
  labs(
    x = "Minimum daily temp",
    y = "Maximum daily temp",
    title = "Temperature scatterplot", 
    caption = "Data from NOAA",
    color = "Location"
  ) + 
  scale_x_continuous(
    breaks = c(-20, 0, 25),
    labels = c("-20C", "0", "25")
  ) + 
  viridis::scale_color_viridis(
    discrete = TRUE
  )

ggsave("plots/weather_scatterplot.png", ggp_temperature)
```

Update my base plot

```{r}
ggp_temperature + # tweaking the plot from before
  theme_minimal() + # white background with grey lines
  # theme_minimal() resets everything, do it in this order
  theme(legend.position = "bottom") # moves legend to bottom so that the plot isn't too small
```

## Adding data in geoms

```{r}
central_park_df =
  weather_df |> 
  filter(name == "CentralPark_NY")

molokai_df = 
  weather_df |> 
  filter(name == "Molokai_HI")

ggplot(data = molokai_df, aes(x = date, y = tmax, color = name)) + 
  geom_point() + 
  geom_line(data = central_park_df) # brings in a different dataset for another part of the plot

```

## `patchwork`

Make three plots and combine using patchwork.


```{r}
ggp_tmax_tmin = 
  weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.5) + 
  theme(legend.position = "none")

ggp_prec_density = 
  weather_df |> 
  filter(prcp > 0) |> 
  ggplot(aes(x = prcp, fill = name)) + 
  geom_density(alpha = 0.5) + 
  theme(legend.position = "none")

ggp_temp_season = 
  weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point(alpha = 0.5) + 
  geom_smooth(se = FALSE) + 
  theme(legend.position = "bottom")

(ggp_tmax_tmin + ggp_prec_density) / ggp_temp_season
# patchwork good for putting multiple plots together

```



## Data manipulation

Let's make temperature violin plots.

```{r}
weather_df |> 
  mutate(name = fct_relevel(name, c("Molokai_HI", "CentralPark_NY", "Waterhole_WA"))) |> # factor orders the variables in a specific order
  ggplot(aes(x = name, y = tmax, fill = name)) + 
  geom_violin(alpha = 0.5)
```


```{r}
weather_df |> 
  mutate(name = fct_reorder(name, tmax)) |> #putting name in order of the tmax (smallest to largest)
  ggplot(aes(x = name, y = tmax, fill = name)) + 
  geom_violin(alpha = 0.5)
# good at looking at the distribution across many categories
```



What about data tidiness??

```{r}
pulse_df = 
  haven::read_sas("data/public_pulse_data.sas7bdat") |> 
  janitor::clean_names() |> 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_", # removes prefix from visit values
    values_to = "bdi"
  ) |> 
  mutate(visit = fct_inorder(visit)) # puts visit in order

pulse_df |> 
  ggplot(aes(x = visit, y = bdi)) + 
  geom_boxplot()
```


Make a plot for the FAS study.

```{r}
pups_df = 
  read_csv("data/FAS_pups.csv", na = c("NA", ".", ""), skip = 3) |> 
  janitor::clean_names() |> 
  mutate(
    sex = case_match(
      sex, 
      1 ~ "male", 
      2 ~ "female"
    )
  )
# pups_df has repeat litter_number

litters_df = 
  read_csv("data/FAS_litters.csv", na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  separate(group, into = c("dose", "tx_day"), sep = 3)
# day is either 7 or 8

fas_df = 
  left_join(pups_df, litters_df, by = "litter_number")
# keps all the rows in pups_df because it has repeats of litter_number while litters_df has unique litter_number

fas_df |> 
  select(pd_ears:tx_day) |> 
  pivot_longer(
    pd_ears:pd_walk,
    names_to = "outcome", 
    names_prefix = "pd_",
    values_to = "pn_day") |> 
  mutate(outcome = fct_reorder(outcome, pn_day)) |> 
  drop_na() |> 
  ggplot(aes(x = dose, y = pn_day)) + 
  geom_violin() + 
  facet_grid(tx_day ~ outcome)

```



